export const ANONYMOUS_TWEETS_REQUEST = 'ANONYMOUS_TWEETS_REQUEST'
export const ANONYMOUS_TWEETS_SUCCESS = 'ANONYMOUS_TWEETS_SUCCESS'
export const ANONYMOUS_TWEETS_FAIL = 'ANONYMOUS_TWEETS_FAIL'

export const MY_TWEETS_REQUEST = 'MY_TWEETS_REQUEST'
export const MY_TWEETS_SUCCESS = 'MY_TWEETS_SUCCESS'
export const MY_TWEETS_FAIL = 'MY_TWEETS_FAIL'

export const NEW_TWEET_REQUEST = 'NEW_TWEET_REQUEST'
export const NEW_TWEET_SUCCESS = 'NEW_TWEET_SUCCESS'
export const NEW_TWEET_FAIL = 'NEW_TWEET_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const TOGGLE_STAR_REQUEST = 'UPDATE_TWEET_REQUEST'
export const TOGGLE_STAR_SUCCESS = 'UPDATE_TWEET_SUCCESS'
export const TOGGLE_STAR_RESET = 'UPDATE_TWEET_RESET'
export const TOGGLE_STAR_FAIL = 'UPDATE_TWEET_FAIL'

export const DELETE_TWEET_REQUEST = 'DELETE_TWEET_REQUEST'
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS'
export const DELETE_TWEET_RESET = 'DELETE_TWEET_RESET'
export const DELETE_TWEET_FAIL = 'DELETE_TWEET_FAIL'